name: Java CI

on:
  push:
    branches: [ Game ]
  pull_request:
    branches: [ Game ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          cd Gomoku
          ./gradlew build --info --build-cache --parallel
#      - name: 上传所有 jar 包
#        uses: actions/upload-artifact@v3
#        with:
#          name: gomoku-jars
#          path: Gomoku/build/libs/*.jar

      - name: 安装 Docker
        uses: docker/setup-buildx-action@v3
      - name: 构建 Docker 镜像
        run: |
          cd Gomoku
          docker build -t gomoku:latest .
      - name: 导出镜像为 tar 文件
        run: |
          docker save -o Gomoku/gomoku-docker.tar gomoku:latest
      - name: 上传镜像 tar 文件
        uses: actions/upload-artifact@v3
        with:
          name: gomoku-docker-tar
          path: Gomoku/gomoku-docker.tar
