name: Sync to GitHub on Push
on: [push]
jobs:
  sync-to-github:
    runs-on: ubuntu-latest
    steps:
      # 1. 使用 ghproxy 镜像站（最稳定）
      - name: Checkout code
        uses: https://ghproxy.com/https://github.com/actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 配置 Git（取消全局镜像，改用代理）
      - name: Configure Git
        run: |
          git config --global user.name "Gitea Sync Bot"
          git config --global user.email "gitea@example.com"
          git config --global push.default current
          # 删除之前的镜像配置（避免冲突）
          git config --global --unset url.https://hub.fastgit.xyz.insteadOf

      # 3. 验证分支（保持不变）
      - name: Verify Branch
        id: branch
        run: |
          CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
          echo "branch=${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
          echo "Current branch: ${CURRENT_BRANCH}"

      # 4. 添加 GitHub remote（原始地址+代理）
      - name: Add GitHub remote
        run: |
          git remote remove github || true
          git remote add github "https://${{ secrets.GH_PAT }}@github.com/HandyWote/BestStrategyOfGomoku.git"
          # 使用代理环境变量
          export http_proxy=http://your-proxy-ip:port
          export https_proxy=http://your-proxy-ip:port
          git fetch github

      # 5. 推送（带重试）
      - name: Push to GitHub
        run: |
          for i in {1..3}; do
            git push github HEAD:${{ steps.branch.outputs.branch }} --force && break
            sleep 5
          done
          echo "Successfully pushed to GitHub"
