name: Sync to GitHub on Push

on: [push]

jobs:
  sync-to-github:
    runs-on: ubuntu-latest
    steps:
      # 1. 使用镜像站加速 checkout
      - name: Checkout code
        uses: https://hub.fastgit.xyz/actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 配置 Git（增加镜像源设置）
      - name: Configure Git
        run: |
          git config --global user.name "Gitea Sync Bot"
          git config --global user.email "gitea@example.com"
          git config --global push.default current
          # 添加 GitHub 镜像源全局配置
          git config --global url."https://hub.fastgit.xyz".insteadOf "https://github.com"

      # 3. 验证分支（保持不变）
      - name: Verify Branch
        id: branch
        run: |
          CURRENT_BRANCH=$(git symbolic-ref --short HEAD)
          echo "branch=${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
          echo "Current branch: ${CURRENT_BRANCH}"

      # 4. 添加 GitHub remote（使用镜像源域名）
      - name: Add GitHub remote
        run: |
          git remote remove github || true
          # 使用镜像站域名替换 github.com
          git remote add github "https://${{ secrets.GH_PAT }}@hub.fastgit.xyz/HandyWote/BestStrategyOfGomoku.git"
          git fetch github

      # 5. 推送（保持不变）
      - name: Push to GitHub
        run: |
          git push github HEAD:${{ steps.branch.outputs.branch }} --force
          echo "Successfully pushed to GitHub"
